name: gwsumm
channels:
  - conda-forge
dependencies:
  # build
  - pip
  - setuptools
  - setuptools-scm
  - wheel
  # install
  - astropy >=3.0.0
  - gwdatafind >=1.1.1
  - gwdetchar >=2.3.2
  - gwpy >=3.0.9
  - gwtrigfind
  - lalsuite
  - lscsoft-glue >=1.60.0
  - lxml
  - markdown
  - MarkupPy
  - matplotlib >=3.5
  - numpy >=1.16
  - pygments >=2.7.0
  - python-dateutil
  - igwn-ligolw
  - scipy >=1.2.0
  # docs
  - numpydoc
  - sphinx
  - sphinx-automodapi !=0.17.0
  - sphinx_bootstrap_theme
  - sphinxcontrib-programoutput
